### ISSUE TITLE
[BUG] Document Description Size Skewed on Large Screens.

### ISSUE THREAD

**Issue by MouseAndKeyboard** [uwasystemhealth/IndEAAv2#105]
## Describe the bug
On large screen resolutions, the document description panel is oversized.

### To Reproduce
Attempt to write a document description on a device with a large screen resolution.

### Expected behavior
Expect to see screen as most users do.

## Other
**Screenshots**
To be added 

**Additional context**

**Comment by frinzekt** [comment]
The possible cause of this is that...

Elements involved:
- Dialog/Modal (allows overflowing)
- Cards (tries to cover the maximum, but will not stretch/overflow which is squishing the content)
