### ISSUE TITLE
Coordinator View - Documents aligned to EOCs

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/IndEAAv2#12]
## What needs to be done
- There should be a user interface during the document upload process which allows the coordinator to give each document a list of general and/or specific EOCs
![175239742-b3017d18-c867-480d-a312-fe44c2c1a6ce](https://user-images.githubusercontent.com/64839317/175466657-ba10d3b0-7310-483e-860a-93d93f8b6ea0.png)

# Other
Documents serve as the way unit coordinators justify their claims that their unit has satisfied several EOCs. For instance, Professor Nef may claim that his unit GENG1234 satisfies EOC 1.1, EOC 2.3 and EOC 2.4. In order to justify the claim, he will upload a document (e.g. lecture slides) that addresses the content outlined in the EOCs above. Therefore, there is a 1 to many relationship between documents and EOC tags. 

Refers to 21 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175466420-c0d12aa5-3f58-4c3c-b604-e8a2e3b91ede.png)

**Comment by MouseAndKeyboard** [comment]
Does this depend on #6 ? The goal of issue 6 is specifically about a particular tag that can be added to issues: the "introduction" tag. If a document is specified as an introduction document then it will be shown in a different location to reviewers.
Could you elaborate a bit more on what you mean here? Thanks :smile:

**Comment by frinzekt** [comment]
> #6

The introduction document is totally irrelevant from this issue. (i have updated the issue)

This issue focuses only on allowing the coordinator add justification and development level (along with that is being able to see all the EOCs that the coordinator can add to)

**Comment by frinzekt** [comment]
However this issue may have some dependency over in #7

**Comment by frinzekt** [comment]
> There should be a user interface during the document upload process which allows the coordinator to give each document a list of general and/or specific EOCs

This part of the of the process of assigning tags to the document has now been done as part of #7 (and the backend change at #47 )

I will be closing this as I will be doing the frontend work of putting documents on the side as part of #24
