### ISSUE TITLE
Reviewer View - 'Review' Listing frontend

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/IndEAAv2#14]
## What needs to be done?
- Reviews need to be viewable in the frontend.
- #13 is required before completing this ticket.
- Refers to this page from IndEAAv1:
![Screen Shot 2022-06-24 at 1 20 59 pm](https://user-images.githubusercontent.com/64839317/175467810-94edf252-beb6-498d-949f-7e5263f85a4a.png)

## Other
Refers to 23 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175467778-cba59846-cd60-4dfa-bfcc-2532f4abfbcd.png)

**Comment by MouseAndKeyboard** [comment]
Could you clarify for me what's meant by making the reviews viewable in the frontend?

My understanding of this issue:
A coordinator wants to see the progress of ongoing reviews (for example, to see if reviewer B is nearly done).
So we will display them together
