### ISSUE TITLE
Reviewer View - (Step 1) Overview and EOC frontend

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/IndEAAv2#15]
## What needs to be done?
- Step 1 of a course evaluation review
- When a reviewer begins reviewing a course evaluation, they are taken to this step, which shows:
- [ ] Introduction documents
- [ ] EOC specifics description & indicators of attainment (organised by EOC general, which can be expanded to view more information)
- #14 is required before completing this issue.
- Refers to this page from IndEAAv1:
![Screen Shot 2022-06-24 at 1 29 14 pm](https://user-images.githubusercontent.com/64839317/175468619-614b1b22-6eac-4bfb-bdfe-23f60cc405cd.png)

## Other
Refers to 24 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175468472-62ff1194-e90c-45f6-8550-ecdd488395f9.png)

**Comment by MouseAndKeyboard** [comment]
Could you elaborate on what you mean by this?

Who should be able to see the EOCs, and where?
My guess: on an evaluation, both the coordinators and reviewers will be presented with a drawer view of the EOC set being used for that evaluation. The user can then click on each general EOC within the set and expand it to view all the specific EOCs.

**Comment by ivy0305** [comment]
> Could you elaborate on what you mean by this?
> 
> Who should be able to see the EOCs, and where? My guess: on an evaluation, both the coordinators and reviewers will be presented with a drawer view of the EOC set being used for that evaluation. The user can then click on each general EOC within the set and expand it to view all the specific EOCs.

Edited the original issue comment with my interpretation & images, I believe this issue refers to what reviewers see, rather than coordinators
