### ISSUE TITLE
Reviewer View - (Step 2) Review Documents

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/IndEAAv2#16]
## What needs to be done?
- Step 2 as part of the course evaluation review
    - A reviewer can review the documents uploaded by a coordinator in the course evaluation
    - They can:
        - [x] See all documents that are part of the course evaluation, including the document title, description, and relevant tags (e.g. EOC general or specifics, introduction)
        - [x] View the document
        - [x] Mark the document as read
        - [x] Add a comment regarding the document
- #15 is required before completing this issue.
- Refers to this page from IndEAAv1:
![Screen Shot 2022-06-24 at 1 39 10 pm](https://user-images.githubusercontent.com/64839317/175469985-e1fc9a03-a992-4a9f-8fba-23af2126ed02.png)

## Other
Refers to 25 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175469848-cad43e89-5031-48fb-939e-676fc9fd9ee6.png)

**Comment by MouseAndKeyboard** [comment]
What exactly is a review document? Is this different to the documents uploaded by coordinators?
My understanding: Coordinators upload documents as supporting evidence that their course has satisfied various EOC specifics. Each reviewer then reads and checks each document and determines whether or not they sufficiently support the EOC specific (and thus the reviewer finally provides a development level for each EOC specific).

So perhaps this point is about giving reviewers a way to comment on documents? Is this different from issue #11 ?

**Comment by ivy0305** [comment]
Edited this, it should be reviewing documents in a course evaluation from a reviewer's perspective :)
