### ISSUE TITLE
Reviewer View - (Step 3) Review Course (front and back end)

### ISSUE THREAD

**Issue by Mechsmith** [uwasystemhealth/IndEAAv2#17]
## What needs to be done?
- Step 3 as part of the course evaluation review
    - A reviewer can evaluate the EOC specifics for the course
    - They can:
        - [ ] See an overview of their given rating (development level), reason, and improvement ideas for EOC specifics that they have already evaluated
        - [ ] If they haven't yet evaluated the EOC specific, opens a modal where they can see more details about that EOC specific, including:
            - [ ] EOC specific number and description
            - [ ] EOC specific's indicators of attainment
            - [ ] The coordinator's justification
            - [ ] Reviewers are able to select their own development level and give a justification this, as well as suggest improvements
            - [ ] View documents related to that EOC specific (including documents tagged with the EOC general & EOC specific)
- Reviewers need to have an interface with which to review the course and associated backend (refer to database schemas for more detail on backend architecture).
- #16 is required before this issue.
- Refers to this page and modal from IndEAAv1:
![Screen Shot 2022-06-24 at 2 23 05 pm](https://user-images.githubusercontent.com/64839317/175475361-3140a3d1-f306-43ad-ae8c-90aec383a12f.png)
![Screen Shot 2022-06-24 at 2 31 15 pm](https://user-images.githubusercontent.com/64839317/175476445-237c6ca6-8b61-4e45-b195-35ce3e072a6f.png)

## Other
Refers to 26 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175476622-e5e6aa41-48e7-4bb2-abb1-f14245107e91.png)

**Comment by MouseAndKeyboard** [comment]
Is this an Epic or an issue? 
Perhaps this issue should actually be completed before all the other reviewer-related issues. My reasoning: If we design/build the general interface for the reviewer flow, we can then populate that flow with specific details.

**Comment by frinzekt** [comment]
I will be completing some portion of the work here in #16 especially the backend part as there's a lot of similarities in permission control (security)
