### ISSUE TITLE
Coordinator View - "General information" page

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#21]
### What needs to be done?
- Frontend for the general information page, which includes:
- [x] Information (review target due date, course evaluation description)
- [x] Introduction documents (documents with the 'introduction' label) - see issue #6 
- [x] Other information (coordinators, date course evaluation was started/made)
- [x] Buttons for:
    - [x] Archive
    - [x] Force completion
    - [x] Manage reviewers
    - [x] Edit evaluation 

![image](https://user-images.githubusercontent.com/104259880/175238106-3783cd48-aa74-4e6d-84fd-53f51935fdca.png)

## Other
Refers to 12 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175462805-38e07315-f8b4-4b5a-a072-dd5cc793503b.png)

**Comment by frinzeUWA** [comment]
The button functionalities seems to have been missed in this issue... but its fine, I'll take care of it somewhere else
