### ISSUE TITLE
Custom EOC's

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#22]
## What needs to be done?

- Backend issue, includes: 
 1. Create a general EOC 
 2. Within an EOC add specific 

- Set of EOC's (one to many relationship - one set of EOC has many general EOC) 
   - When a new course evaluation is created, the EOC set will be duplicated - this prevents issues (e.g. old course evaluation EOCs edited and no longer matching) if EOCs are changed in the future 

- **Note:** This will be edited by an administrator using Django admin. We do not need a frontend for this.

### Terminology 
Set of EOC's:
![image](https://user-images.githubusercontent.com/104259880/175239485-7b830a43-c834-4087-b381-b9388e41027f.png)

General EOC's: 
![175239485-7b830a43-c834-4087-b381-b9388e41027f](https://user-images.githubusercontent.com/64839317/175462512-953cfb5b-3cc2-4cf1-9dc1-1280d1ff8dd8.png)

Specific EOC's within a general EOC:
![175239742-b3017d18-c867-480d-a312-fe44c2c1a6ce](https://user-images.githubusercontent.com/64839317/175462675-81d4ce33-9fa6-4aa7-84f4-503bf820f6e6.png)

### Context
Refers to 13 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175462245-94de6def-fb3a-4450-9015-22f707ba57b4.png)

**Comment by frinzekt** [comment]
I will be tackling this in certain extent but not a priority for me in #34 because part of the thing I would like to demonstrate in the API endpoint is serialisers

**Comment by frinzekt** [comment]
I will not be completely closing this

> When a new course evaluation is created, the EOC set will be duplicated - this prevents issues (e.g. old course evaluation EOCs edited and no longer matching) if EOCs are changed in the future
As I do no aim to fulfill this in my task

**Comment by frinzekt** [comment]
closing this because

> Create a general EOC
Within an EOC add specific

has been tackled

> Set of EOC's (one to many relationship - one set of EOC has many general EOC). When a new course evaluation is created, the EOC set will be duplicated - this prevents issues (e.g. old course evaluation EOCs edited and no longer matching) if EOCs are changed in the future.

This is the only thing that is not done. However, let's discuss this in the future.
