### ISSUE TITLE
Coordinator View - Backend for EOC Justification and Development Level

### ISSUE THREAD

**Issue by chayG5** [uwasystemhealth/IndEAAv2#23]
## What needs to be done?
- Backend issue
- Ability to add justification and development level for a group of EOC specific 
   - The grouped specific EOC's have the same justification
      - Editing the justification for one EOC specific will edit all justifications for checked EOC specifics
- Validation (Justifications do not overlap for EOC specifics i.e. an EOC specific can only have one justification) 

![image](https://user-images.githubusercontent.com/104259880/175240532-44f80a5a-7baf-4a07-b66e-a0e20648fa83.png)

## Other
Refers to 14 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175461620-8dbc4420-73ca-4975-be4f-3a7c5cbcfeff.png)

**Comment by frinzekt** [comment]
I am going to be doing this alongside #24 in one-branch (bundling it for full-stack development)
