### ISSUE TITLE
Create a wireframe mockup / design the interface

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#26]
## What needs to be done?
RE-design (and prototype) the UI design. The goal of this task is to:
- Visualise different pages
- Outline the user navigation workflow (how the user navigates from one page to another)
- [Figma link for IndEAAv2](https://www.figma.com/file/Y7btfNdl5TD2Qs5bpvAPav/IndEAAv2?node-id=0%3A1)

## Additional info
- Decide on a colour scheme so we can keep everything consistent!
- It may be useful to create frames and include the issue number in the name. Example with ASER below:
![Screen Shot 2022-06-24 at 12 06 48 pm](https://user-images.githubusercontent.com/64839317/175460279-eb652862-59c9-4e8e-8258-04119534d4e4.png)

**Comment by MouseAndKeyboard** [comment]
https://www.figma.com/file/Y7btfNdl5TD2Qs5bpvAPav/IndEAAv2?node-id=0%3A1

**Comment by frinzekt** [comment]
I just realised we have an old design for Indeaa https://www.figma.com/proto/JyKdznpEaxg9xVtSyQXItZ/Indeaa?node-id=0%3A1 @chayG5

**Comment by frinzekt** [comment]
https://www.figma.com/file/JyKdznpEaxg9xVtSyQXItZ/Indeaa?node-id=4%3A0

**Comment by frinzekt** [comment]
I will be closing this issue because most of the work of this has been done. Thanks @ivy0305  and @chayG5!

We will just update it when we see fit or there's some future pages that we have to redesign
