### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#27]
## What needs to be done?
- Include information (e.g. requirement docs)
- Option to login with Google from this page
- Will replace the following page:
<img width="1497" alt="Screen Shot 2022-06-23 at 6 20 49 pm" src="https://user-images.githubusercontent.com/64839317/175277262-88d0ca25-dfe1-4870-b088-648c778c0a88.png">

**Comment by frinzekt** [comment]
closed by merge #41
