### ISSUE TITLE
Deployment of frontend & backend

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#32]
## What needs to be done?
Similarly to issue #31, deploy the frontend & backend to the VPS. This can be done after issue #27 has been completed.

**Comment by MouseAndKeyboard** [comment]
I guess this and issue #31 acheive the same thing? Since the whole project is using docker-compose, deploying in one place will deploy the documentation, frontend, backend, etc all at the same time

**Comment by frinzekt** [comment]
> I guess this and issue #31 acheive the same thing? Since the whole project is using docker-compose, deploying in one place will deploy the documentation, frontend, backend, etc all at the same time

@MouseAndKeyboard  yeah sortta... I just need to create two files
- `docker-compose-prod.yml` to make sure I only run the necessary services
- `redeploy.sh`... just a small script to make deployment easier

and setup the `.env` in production... (hey @peter-tanner, can we book a time together to do this task? I need you as part of the #29, but I think it's worth for you to know how to deploy in a production VPS to know whats involved running a web service that is developed)
