### ISSUE TITLE
Backend API for Course Evaluation

### ISSUE THREAD

**Issue by ivy0305** [uwasystemhealth/IndEAAv2#34]
## What needs to be done?
- For the list view, linked to issue #33 

## Other
Refers to 10 from our discussion
![MicrosoftTeams-image](https://user-images.githubusercontent.com/64839317/175478495-9fc4340f-9909-4ea1-81a0-122894564d10.png)

**Comment by MouseAndKeyboard** [comment]
![image](https://user-images.githubusercontent.com/31727915/175469806-18c31439-f046-4561-a8ca-94af964da833.png)

Should support basic CRUD operations.
