### ISSUE TITLE
Review initial issues

### ISSUE THREAD

**Issue by MouseAndKeyboard** [uwasystemhealth/IndEAAv2#37]
## What needs to be done?
Just going through all the created issues and ensuring there is sufficient context provided so people know what's going on/what needs to be done.

Review issues:
- [x] 1-10
- [x] 11-20
- [x] 21-30
- [x] >31

- [x] Add priorities to issues

Important because 3 of us won't be here next week (27th - 30th) so we need to make sure issues are assigned/good.

**Comment by MouseAndKeyboard** [comment]
done

**Comment by frinzekt** [comment]
then close it if its done
