### ISSUE TITLE
Coordinator View - Frontend for Create and update documents 

### ISSUE THREAD

**Issue by peter-tanner** [uwasystemhealth/IndEAAv2#7]
## What needs to be done?
A dialog which allows a coordinator to change the name, description and link to the document. The tag can also be changed which allows the document to be visible in an EOC or the introduction (#6). 

The create and update dialogs use the same interface.
## Other
Documents are the way in which a coordinator provides evidence to reviewers. For example, if a coordinator claims that their unit adequately satisfies the EOC relating to teaching students to appropriate statistical techniques, they will upload classwork or lecture slides that demonstrate this. So: the upload dialog should only be accessible to coordinators.

Refers to 19 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175465132-2d3c5b02-2e83-49c5-9eba-a5bde9628e41.png)

**Comment by frinzekt** [comment]
I am taking over this @peter-tanner  FYI
