### ISSUE TITLE
Coordinator View - Backend create view and update view of document

### ISSUE THREAD

**Issue by peter-tanner** [uwasystemhealth/IndEAAv2#8]
## What needs to be done?
Creation of a document should do the following:
1. Create a new document in the `documents` table, with the id of the `courseEvaluation` it is being created in.
2. For the new entry, modify the `isInIntroduction`, `eocGeneral` and `eocSpecific` fields based on the options selected by the user in the tags field. Also modify the `description`, `name` and `link` based on the options provided. See #7 

Updating a document performs step 2 of the above on an already existing entry in the `documents` table
## Other
Refers to 18 from our discussion
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/64839317/175465206-5fc6b28c-4596-423d-bae8-66ee206f0e33.png)

**Comment by MouseAndKeyboard** [comment]
Is it possible for this issue to be completed independently from #7 ? Seems like they are essentially the same issue.

**Comment by frinzekt** [comment]
just making you aware @peter-tanner , I have crossed over this issue due to the PR initially created by Michael as part of #47 (yes i know its totally irrelevant, but the change has been crossed)
